{{- if and .Values.myPod.isAuth .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
{{- end }}